language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
after_success:
- npm run coverage
env:
  global:
    - CC_TEST_REPORTER_ID=164b291f2472b5ae445e2a8b65adb124e17b96c0134c6b3f54e709cc21df5dcf
language: node_js
rvm:
  - 2.2.0
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  email:false
